message/urls.py
from django.conf.urls import url

import message.views

urlpatterns = [
    url(r'^message/$', message.views.message, name='message'),
    url(r'^read/(?P<id>\d+)/$', message.views.read, name='read'),
    url(r'^read_sent_message/(?P<id>\d+)/$', message.views.read_sent_message, name='read_sent_message'),
    url(r'^create/$', message.views.create, name='create'),
    url(r'^read/trash/(?P<id>\d+)/$', message.views.read_draft, name='read_draft'),
    url(r'^draft/$', message.views.draft, name='draft'),
    url(r'^sent_message/$', message.views.sent_message, name='sent_message'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.http import HttpResponse
import django.contrib.auth.urls

import pet.urls
import message.urls
import accounts.urls
import pet.views

admin.autodiscover()

urlpatterns = [
    url(r'', include(pet.urls, namespace='world')),
    url(r'^$', pet.views.index),
    url(r'^account/', include(django.contrib.auth.urls)),
    url(r'^account/', include(accounts.urls)),
    url(r'^secert/', include(admin.site.urls)),
    url(r'^message/', include(message.urls, namespace="message")),
    url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain")),
    # url(r'^admin/', include('admin_honeypot.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

pet/urls.py
from django.conf.urls import url

import pet.views

urlpatterns = [
    url(r'^display/$', pet.views.display, name='display'),
    url(r'^picture/$', pet.views.picture_creator, name='picture_creator'),
    url(r'^board/$', pet.views.board_creator, name='board_creator'),
    url(r'^register/$', pet.views.pet_registration, name='petRegistration'),
    url(r'^login/$', pet.views.login_request, name='login_request'),
    url(r'^logout/$', pet.views.logout_request, name='logout_request'),
    url(r'^profile/(?P<slug>[-\w\d]+)/$', pet.views.profile, name='profile'),
    url(r'^friend/add/(?P<to_username>[\w-]+)/$', pet.views.friendship_add_friend, name='friendship_add_friend'),
    url(r'^show_followers/add/(?P<followee_username>[\w-]+)/$', pet.views.follower_add, name='follower_add'),
    url(r'^archive/$', pet.views.archive, name='archive'),
    url(r'^board/(?P<slug>[-\w\d]+),(?P<id>\d+)/(?P<picture_id>\d+)$', pet.views.description, name='description'),
    url(r'^show_following/$', pet.views.show_followers, name='show_followers'),
    url(r'^boardfinder/$', pet.views.board_finder, name='board_finder'),
    url(r'^boardeditor/$', pet.views.board_editor, name='board_editor'),
    url(r'^changepicture/(?P<picture_id>\d+)/$', pet.views.change_picture, name='change_picture'),
    url(r'^show_following/(?P<slug>[-\w\d]+)/cancelfriend/$', pet.views.cancel_friend, name='cancel_friend'),
    url(r'^show_following/(?P<slug>[-\w\d]+)/addfriend/$', pet.views.add_friend, name='add_friend'),
    url(r'^my_friend/$', pet.views.my_friend, name='my_friend'),
    url(r'^Follow/$', pet.views.show_following, name='show_following'),
    url(r'^sparkprofile/$', pet.views.spark_profile, name='spark_profile'),
    url(r'^search_person/$', pet.views.search_person, name='search_person'),
    url(r'^followingall/$', pet.views.following_all, name='following_all'),
    url(r'^whatisparkalight/$', pet.views.whatspark, name='whatspark'),
    url(r'^contact/$', pet.views.contacts, name='contact'),
    url(r'^edit_friend_func/$', pet.views.edit_friend_func, name='edit_friend_func'),
    url(r'^friend_star/(?P<slug>[-\w\d]+)/$', pet.views.friend_star, name='friend_star'),
    url(r'^term-and-condition/$', pet.views.term, name='term'),
    url(r'^privacy-policy/$', pet.views.privacy, name='privacy'),
    url(r'^faq/$', pet.views.faq, name='faq'),
    url(r'^car/like$', pet.views.like, name='like'),
    url(r'^car/postComment$', pet.views.post_comment, name='post_comment'),
    url(r'^car/getComment$', pet.views.get_comment, name='get_comment'),
    url(r'^car/deleteComment$', pet.views.delete_comment, name='delete_comment'),
    url(r'^board/(?P<slug>[-\w\d]+),(?P<id>\d+)/$', pet.views.car, name='car'),
    url(r'^car/search$', pet.views.board_finder, name='search'),
    url(r'^car/searchBoards$', pet.views.search_boards, name='search_boards'),
    url(r'^friend/accept/(?P<friendship_request_id>\d+)/$', pet.views.friendship_accept, name='friendship_accept'),
    url(r'^friend/cancelss/(?P<username>[\w-]+)/$', pet.views.friendship_cancel, name='friendship_cancel'),
    url(r'^show_followers/remove/(?P<followee_username>[\w-]+)/$', pet.views.follower_remove, name='follower_remove'),
    url(r'^friend/remove/(?P<friendship_request_id>\d+)/$', pet.views.friendship_reject, name='friendship_reject'),
]

pet/models.py
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser, PermissionsMixin)
from django.db import models
from django.template.defaultfilters import slugify


class PersonManager(BaseUserManager):
    def create_user(self, email, date_of_birth, username, password=None, ):
        if not email:
            msg = 'Users must have an email address'
            raise ValueError(msg)

        if not username:
            msg = 'This username is not valid'
            raise ValueError(msg)

        if not date_of_birth:
            msg = 'Please Verify Your DOB'
            raise ValueError(msg)

        user = self.model(
            email=PersonManager.normalize_email(email), username=username, date_of_birth=date_of_birth)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password, date_of_birth):
        user = self.create_user(email, password=password, username=username, date_of_birth=date_of_birth)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Person(AbstractBaseUser, PermissionsMixin):
    inbox = (
        ('A', 'Activate'),
        ('D', 'Deactivate'),
        ('F', 'Permit To Friends Only'),
    )

    email = models.EmailField(verbose_name='email address', max_length=255, unique=True, blank=True, null=True)
    username = models.CharField(max_length=255, unique=True, db_index=True, )
    date_of_birth = models.DateField(blank=True, null=True)
    name = models.CharField(max_length=3200, blank=True)
    image = models.ImageField(upload_to='photos', blank=True)
    description = models.CharField(max_length=250, blank=True)
    slug = models.SlugField()
    inbox = models.CharField(max_length=3200, choices=inbox, default='A')
    profile = models.BooleanField(default=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'date_of_birth', ]

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    objects = PersonManager()

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.username)
        super(Person, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.username


class Board(models.Model):
    SHIRT_SIZES = (

        ('1', 'Adventure Recreation'),
        ('1', 'Animal'),
        ('2', 'Architecture'),
        ('3', 'Art'),
        ('4', 'Convention'),
        ('5', 'Fashion'),
        ('6', 'Festival'),
        ('7', 'Food'),
        ('8', 'Holiday'),
        ('9', 'Literature'),
        ('10', 'Music'),
        ('11', 'Outdoor Recereation'),

    )
    shirt_size = models.CharField(max_length=3200, choices=SHIRT_SIZES)
    user = models.ForeignKey(Person, on_delete=models.CASCADE)
    name = models.CharField(max_length=55)
    profile = models.BooleanField(default=True)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=300, blank=True)
    comments = models.BooleanField(default=True)
    friends = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.name)
        super(Board, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

    def pic(self):
        p = Picture.objects.get(is_primary=True, board=self)
        return p.image.url

    def pic_image(self):
        p = Picture.objects.get(is_primary=True, board=self)
        return p.image


class Picture(models.Model):
    user = models.ForeignKey(Person, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, blank=False, null=False, related_name='board', on_delete=models.CASCADE)
    description = models.CharField(blank=False, max_length=3200)
    created = models.DateTimeField(auto_now_add=True)
    is_primary = models.BooleanField(default=False)
    image = models.ImageField(upload_to='whatever', blank=True)

    def delete(self, *args, **kwargs):
        self.image.delete(False)
        super(Picture, self).delete(*args, **kwargs)

    def __unicode__(self):
        return self.description


class BoardComment(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(Person, on_delete=models.CASCADE)
    body = models.CharField(max_length=300, blank=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.user.username


class LikeBoard(models.Model):
    user = models.ForeignKey(Person, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class Contact(models.Model):
    BUSINESS = 'BUSINESS'
    General = 'GENERAL'
    Account = 'My Account'
    Technical = 'Technical Problem'
    Feedback = 'Feedback'
    Others = 'Others'
    CATEGORY = (
        (General, 'General'),
        (Account, 'My Account'),
        (Technical, 'Technical Problem'),
        (Feedback, 'Feedback'),
        (Others, 'Others'),
    )
    Category = models.CharField(max_length=3200, choices=CATEGORY)
    text = models.CharField(blank=False, max_length=200)
    email = models.EmailField(blank=False)
    user = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.user.username

pet/templates/archive.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    {% load static %} {% load thumbnail %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content=""> {% load static %}
    <title>SparkaLight</title>
    <!-- Bootstrap core CSS -->
    <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static '/css/theme.css' %}">
    <!-- Custom styles for this template -->
    <!--  <link href="style.css" rel="stylesheet"> -->
</head>

<body class="green-bg archive">


    <div class="container pt-2">
        <header>


            <div class="row sp-head-holder">
                <div class="col-sm-4 logo-holder order-sm-2 red-bg">
                    <a href="/" class="logo hs white">SparkaLight</a>
                </div>

                <div class="col-sm-3 ml-auto order-sm-1 m-blue-bg sp-nav-holder">
                    <ul class="list-inline sp-nav mb-0 text-sm-center">
                        <li class="list-inline-item">
                            <a href="{% url "world:profile" person.slug %}" class="hs white">Profile</a>
                        </li>
                        <li class="list-inline-item">
                            <a href="{% url "message:message" %}" class="hs white">Inbox</a>
                        </li>
                    </ul>
                </div>


                <div class="col-sm-3 mr-auto order-sm-3 m-blue-bg sp-nav-holder">
                    <ul class="list-inline mb-0 sp-nav text-sm-center">
                        <li class="list-inline-item">
                            <a href="{% url "world:board_finder" %}" class="hs white">Explore</a>
                        </li>
                        <li class="list-inline-item">
                            <a href="{% url "world:board_creator" %}" class="hs white">Create</a>
                        </li>
                    </ul>
                </div>

                <a href="{% url "world:logout_request" %}" class="logout br red-bg white">logout</a>
            </div>

        </header>

    </div>
    <!-- container -->

    <div class="container container-wide">

        <div class="row">
            <div class="col-md-4">
                <div class="title-holder">
                    <div class="col-sm-12 mb-1 orange-bg white text-center">
                        <h2 class="br my-0">recent comments</h2>
                    </div>
                </div>
                <div class="box">

                </div>
            </div>
            <div class="col-md-8">
                <div class="title-holder">
                    <div class="col-sm-12 mb-1 orange-bg white text-center">
                        <h2 class="hs my-0">Archive</h2>
                    </div>
                </div>
                <div class="box">
                    <div class="row">
                        <div class="col-sm-4">

                        </div>

                        <div class="col-sm-4">

                        </div>

                        <div class="col-sm-4">

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="{% static "javascript/jquery-1.9.1.min.js" %}"></script>
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

</body>

</html>


<!--
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">

<head>
    {% load static %}
    <script type="text/javascript" src="{% static " javascript/jquery-1.9.1.min.js " %}"></script>
    <script type="text/javascript" src="{% static " javascript/jquery.columnizer.js " %}"></script>
    <script type="text/javascript" src="{% static " javascript/jquery.lazyload.min.js " %}"></script>

    <script type="text/javascript">
        $(function () {
            $('h1').addClass('dontend');
            $('.wide').columnize({
                width: 235,
                height: 520
            });
        });
    </script>


    <script type="text/javascript">
        {% verbatim %}
        jQuery(document).ready(function ($) {
            $("img.lazy").lazyload(
                {
                    data_attribute: "orig"
                });
        }); {% endverbatim %}
    </script>

    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static "css/archive.css" %}"> {% load thumbnail %}

</head>

<div class="box3"></div>
<div class="box4"></div>
<a class="theLink" href="{% url "world:logout_request" %}">
    <div class="cake2">logout</div>
</a>


<a class="theLink" href="{% url "world:profile" person.slug %}">
    <div class="box9">Profile</div>
</a>
<a class="theLink" href="{% url "message:message" %}">
    <div class="box10">Inbox</div>
</a>
<a class="theLink" href="{% url "world:board_finder" %}">
    <div class="box11">Explore</div>
</a>
<a class="theLink" href="{% url "world:board_creator" %}">
    <div class="box12">Create</div>
</a>
<div class="cake1">SparkaLight</div>

<div class="box13">Archive</div>


<div class="box15">recent comments</div>


<div class="endless_page_template">
    {% include C %}
</div>


<div class="endless_page_template">
    {% include P %}
</div>
<script type="text/javascript" src="{% static "el-pagination/js/el-pagination.js" %}"></script>
<script type="text/javascript">$.endlessPaginate();</script>
-->

pet/templates/boardeditor.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
{% load static %}
<link rel="stylesheet" href="{% static "css/editboard.css" %}">
<div class="container">

</div>

<div class="block">


    {{ form.hidden_field }}{{ form.hidden_field }}{{ form.hidden_field }}{{ form.hidden_field }}


    <p> Edit Board Description</p>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ BoardChangeNameForm.as_p }}
        <input type="hidden" name="process" value="change"/>
        <input type="submit" value="find" class="orange"/>

    </form>
    {% if form %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="process" value="changename"/>
            <input type="submit" value="save" class="color"/>
        </form>

    {% endif %}



    <p> Change boardname</p>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ board.as_p }}
        <input type="hidden" name="process" value="third"/>
        <input type="submit" value="save" class="orange"/>
    </form>


    <p> Special settings for your board</p>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ BoardPrivateForm.as_p }}
        <input type="hidden" name="process" value="special"/>
        <input type="submit" value="find" class="orange"/>

    </form>

    {% if forms %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p> {{ forms.username.profile }}<label for="profile">Board is Public</label>{{ forms.profile }} </p>
            <p> {{ forms.username.friends }}<label for="friends">Only allow friends to
                comment</label>{{ forms.friends }} </p>
            <p> {{ forms.username.comments }}<label for="comments">Enable Comments</label>{{ forms.comments }} </p>
            <input type="hidden" name="d" value="{{ c.id }}"/>

            <input type="hidden" name="process" value="specials"/>
            <input type="submit" value="save" class="color"/>

        </form>
    {% endif %}

</div>


<a class="theLink" href="{% url "world:show_followers" %}">
    <div class="box1 theLink">FOLLOWER</div>
</a>
<a class="theLink" href="{% url "world:show_following" %}">
    <div class="box2">FOLLOWING</div>
</a>
<a class="theLink" href="{% url "world:search_person" %}">
    <div class="box3">SEARCH</div>
</a>
<div class="box4">edit board</div>
<a class="theLink" href="{% url "world:profile" person.slug %}">
    <div class="box5">Return back To Profile</div>
</a>
<a class="theLink" href="{% url "world:logout_request" %}">
    <div class="box7">Logout</div>
</a>

pet/templates/contactform.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
{% load static %}
<link rel="stylesheet" href="{% static "css/contactform.css" %}">
<div class="cake1"></div>
<span id="cake2">SparkaLight</span>
<span id="cake3">Contact Form</span>
<span id="cake4">email :</span>
<a class="theLink" href="{% url "world:term" %}"><span id="cake7">term and condition</span></a>
<a class="theLink" href="{% url "world:privacy" %}"><span id="cake8">privacy and policy</span></a>

<a class="theLink" href="{% url "world:profile" person.slug %}"><span id="cake9">Return to Profile</span></a>
<form method="POST">
    {% csrf_token %}
    {{ form.Category }}
    {{ form.text }}
    {{ form.email }}
    <span id="cake10">{{ form.email.errors }}</span>
    <span id="cake11">{{ form.text.errors }}</span>

    <input type="submit" value="submit" id="submit"/>
</form>
<span id="cake6">Your request will be answered via email</span>

pet/templates/editfriend.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
{% load static %}
<head>

    {% load thumbnail %}


    <script type="text/javascript" src="{% static "javascript/jquery-1.9.1.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "css/editfollowingall.css" %}">


    <meta charset="utf-8"/>


</head>

<div class="container">

</div>

<div class="block">
    <br>

    <c> Click on a user if you wish to <br>remove them as a friend</c>


</div>


<div class="endless_page_template">
    {% include page_template %}
</div>
<script type="text/javascript" src="{% static "el-pagination/js/el-pagination.js" %}"></script>
<script type="text/javascript">$.endlessPaginate();</script>


<a class="theLink" href="{% url "world:show_followers" %}">
    <div class="box1">FOLLOWER</div>
</a>
<a class="theLink" href="{% url "world:show_following" %}">
    <div class="box2">FOLLOWING</div>
</a>
<a class="theLink" href="{% url "world:search_person" %}">
    <div class="box3">SEARCH</div>
</a>
<div class="box10">Settings for your friends</div>
<a class="theLink" href="{% url "world:profile" request.user.slug %}">
    <div class="box5">Return back To Profile</div>
</a>
<a class="theLink" href="{% url "world:logout_request" %}">
    <div class="box7">Logout</div>
</a>
<a class="theLink" href="{% url "world:my_friend" %}">
    <div class="box9">Return To Friends</div>
</a>

pet/templates/profile.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    {% load static %} {% load thumbnail %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
     {% load static %}
    <title>SparkaLight</title>
    
    <!-- Bootstrap core CSS -->
   <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static '/css/theme.css' %}">
    <!-- Custom styles for this template -->
  <!--  <link href="style.css" rel="stylesheet"> -->
</head>

<style>
</style>

<body class="blue-bg mt-2 profile">


    <div class="container pt-2 sp-h-100 yellow-bg">
        <header>
            <div class="row">
                <div class="col-sm-12 mb-4 text-right">
                    {% if user.is_authenticated %}
                    <a href="{% url "world:logout_request" %}" class="red br fs-17 logout">
                        <u>logout</u>
                    </a>
                    {% endif %}
                </div>
            </div>

            <div class="row sp-head-holder">
                <div class="col-sm-4 logo-holder order-sm-2 white-bg">
                    <a href="/" class="logo hs yellow">SparkaLight</a>
                </div>

                <div class="col-sm-3 ml-auto order-sm-1 white-bg sp-nav-holder">
                    <ul class="list-inline sp-nav mb-0 text-sm-center">
                        <li class="list-inline-item">
                            <a href="{% url "world:archive" %}" class="hs red">Archive</a>
                        </li>
                        <li class="list-inline-item">
                            <a href="{% url "world:board_finder" %}" class="hs red">Explore</a>
                        </li>
                    </ul>
                </div>


                <div class="col-sm-3 mr-auto order-sm-3 white-bg sp-nav-holder">
                    <ul class="list-inline mb-0 sp-nav text-sm-center">
                        <li class="list-inline-item">
                            <a href="/Follow" class="hs red">Following</a>
                        </li>
                        <li class="list-inline-item">
                            <a href="{% url "world:board_creator" %}" class="hs red">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>

        <div class="row">
            <div class="col-sm-6 mb-1 mr-auto ml-auto blue-bg text-center">
                <h2 class="hs my-0">{% if person %} {{ person.name }}{% endif %}</h2>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6 order-sm-2 text-center">
                {% if person.image %}{% thumbnail person.image "250x250" as im %}
                <img src="{{ im.url }}" class="my-5 img-fluid"> 
                {% endthumbnail %}
                {% else %}
                    <div class="text-center avy-missing ml-auto mr-auto">
                        <span class="d-inline-block w-100 question blue pr">?</span>
                        <span class="ma-text blue pr">Missing avatar</span>
                    </div>
                {% endif %}


                <!-- <img src="http://via.placeholder.com/250x250" class="my-5 img-fluid"> -->
            </div>

            <div class="col-sm-6 my-sm-5 order-sm-1">
                <div class="box blue-bg p-3 pt-2 pb-2">
                    <p>{% if person %} {{ person.description }}{% endif %}</p>
                </div>
                {% if person == request.user %}
                <a href="{% url "world:display" %}" class="blue br">Edit Profile</a>
                {% else %}{% if not Follows %} {% endif %} {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <a href="/board" class="btn red-bg white hs w-100 b-link">Board</a>
            </div>

            <div class="col-sm-12">
                {% if user.is_authenticated %}{% if not person == request.user %}{% if not Friend %}{% if not already %}
                <a class="theLink" href="{% url " world:friendship_add_friend " person.username %}">
                    <div id="box26"> Add as friend</div>
                </a>{% endif %}{% endif %}{% endif %}{% endif %}
                
                
                <div class="endless_page_template text-center">
                    {% include page_template %}
                </div>
                <script type="text/javascript" src="{% static " el-pagination/js/el-pagination.js " %}"></script>
                <script type="text/javascript">$.endlessPaginate();</script>
            </div>
        </div>
    </div>
    <!-- container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="{% static "javascript/jquery-1.9.1.min.js" %}"></script>
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

</body>

</html>


<!--
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<head>
    {% load static %}
    {% load thumbnail %}
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="{% static "css/profile.css" %}">
    <link rel="stylesheet" href="{% static "css/road.css" %}">

    <script type="text/javascript" src="{% static "javascript/jquery-1.9.1.min.js" %}"></script>


</head>


<div class="b11"></div>


<div class="box1"></div>
<div class="box2"> SparkaLight</div>
<div class="box3"></div>
<div class="box4"></div>
<div class="box5"> {% if person %} {{ person.name }}{% endif %}</div>
<div class="box6">{% if person %} {{ person.description }}{% endif %}</div>
<div class="box8">{% if person.image %}{% thumbnail person.image "250x250" as im %}
    <img src="{{ im.url }}">
{% endthumbnail %}{% else %}
    <div class="box20"><span class="box21">?</span><span class="box22">Missing avatar</span></div>{% endif %}</div>
<div class="box9">Board</div>


<a class="theLink" href="/Follow">
    <div class="box12">Following</div>
</a>
<a class="theLink" href="{% url "world:archive" %}">
    <div class="box13"> Archive</div>
</a>
<a class="theLink" href="{% url "world:board_finder" %}">
    <div class="box14"> Explore</div>
</a>
<a class="theLink" href="{% url "world:board_creator" %}">
    <div class="box15"> Create</div>
</a>

<div class="box16"></div>
<div class="b9"></div>
{% if user.is_authenticated %}<a class="theLink" href="{% url "world:logout_request" %}">
    <div class="box17">logout</div>
</a>{% endif %}

{% if person == request.user %}<a class="theLink" href="{% url "world:display" %}">
    <div class="box18">edit Profile</div>
</a>{% else %}{% if not Follows %}

    {% if user.is_authenticated %}<a class="theLink" href="{% url "world:follower_add" person.username %}">
        <div id="box23"><span id="box24">Spark</span></div>
    </a>{% endif %}

{% endif %}
{% endif %}




{% if user.is_authenticated %}{% if not person == request.user %}{% if not Friend %}{% if not already %}
    <a class="theLink" href="{% url "world:friendship_add_friend" person.username %}">
        <div id="box26"> Add as friend</div>
    </a>{% endif %}{% endif %}{% endif %}{% endif %}


<div class="endless_page_template">
    {% include page_template %}
</div>
<script type="text/javascript" src="{% static "el-pagination/js/el-pagination.js" %}"></script>
<script type="text/javascript">$.endlessPaginate();</script>




-->