message/urls.py
from django.conf.urls import url

import message.views

urlpatterns = [
    url(r'^message/$', message.views.message, name='message'),
    url(r'^read/(?P<id>\d+)/$', message.views.read, name='read'),
    url(r'^read_sent_message/(?P<id>\d+)/$', message.views.read_sent_message, name='read_sent_message'),
    url(r'^create/$', message.views.create, name='create'),
    url(r'^read/trash/(?P<id>\d+)/$', message.views.read_draft, name='read_draft'),
    url(r'^draft/$', message.views.draft, name='draft'),
    url(r'^sent_message/$', message.views.sent_message, name='sent_message'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.http import HttpResponse
import django.contrib.auth.urls

import pet.urls
import message.urls
import accounts.urls
import pet.views

admin.autodiscover()

urlpatterns = [
    url(r'', include(pet.urls, namespace='world')),
    url(r'^$', pet.views.index),
    url(r'^account/', include(django.contrib.auth.urls)),
    url(r'^account/', include(accounts.urls)),
    url(r'^secert/', include(admin.site.urls)),
    url(r'^message/', include(message.urls, namespace="message")),
    url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain")),
    # url(r'^admin/', include('admin_honeypot.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

pet/urls.py
from django.conf.urls import url

import pet.views

urlpatterns = [
    url(r'^display/$', pet.views.display, name='display'),
    url(r'^picture/$', pet.views.picture_creator, name='picture_creator'),
    url(r'^board/$', pet.views.board_creator, name='board_creator'),
    url(r'^register/$', pet.views.pet_registration, name='petRegistration'),
    url(r'^login/$', pet.views.login_request, name='login_request'),
    url(r'^logout/$', pet.views.logout_request, name='logout_request'),
    url(r'^profile/(?P<slug>[-\w\d]+)/$', pet.views.profile, name='profile'),
    url(r'^friend/add/(?P<to_username>[\w-]+)/$', pet.views.friendship_add_friend, name='friendship_add_friend'),
    url(r'^show_followers/add/(?P<followee_username>[\w-]+)/$', pet.views.follower_add, name='follower_add'),
    url(r'^archive/$', pet.views.archive, name='archive'),
    url(r'^board/(?P<slug>[-\w\d]+),(?P<id>\d+)/(?P<picture_id>\d+)$', pet.views.description, name='description'),
    url(r'^show_following/$', pet.views.show_followers, name='show_followers'),
    url(r'^boardfinder/$', pet.views.board_finder, name='board_finder'),
    url(r'^boardeditor/$', pet.views.board_editor, name='board_editor'),
    url(r'^changepicture/(?P<picture_id>\d+)/$', pet.views.change_picture, name='change_picture'),
    url(r'^show_following/(?P<slug>[-\w\d]+)/cancelfriend/$', pet.views.cancel_friend, name='cancel_friend'),
    url(r'^show_following/(?P<slug>[-\w\d]+)/addfriend/$', pet.views.add_friend, name='add_friend'),
    url(r'^my_friend/$', pet.views.my_friend, name='my_friend'),
    url(r'^Follow/$', pet.views.show_following, name='show_following'),
    url(r'^sparkprofile/$', pet.views.spark_profile, name='spark_profile'),
    url(r'^search_person/$', pet.views.search_person, name='search_person'),
    url(r'^followingall/$', pet.views.following_all, name='following_all'),
    url(r'^whatisparkalight/$', pet.views.whatspark, name='whatspark'),
    url(r'^contact/$', pet.views.contacts, name='contact'),
    url(r'^edit_friend_func/$', pet.views.edit_friend_func, name='edit_friend_func'),
    url(r'^friend_star/(?P<slug>[-\w\d]+)/$', pet.views.friend_star, name='friend_star'),
    url(r'^term-and-condition/$', pet.views.term, name='term'),
    url(r'^privacy-policy/$', pet.views.privacy, name='privacy'),
    url(r'^faq/$', pet.views.faq, name='faq'),
    url(r'^car/like$', pet.views.like, name='like'),
    url(r'^car/postComment$', pet.views.post_comment, name='post_comment'),
    url(r'^car/getComment$', pet.views.get_comment, name='get_comment'),
    url(r'^car/deleteComment$', pet.views.delete_comment, name='delete_comment'),
    url(r'^board/(?P<slug>[-\w\d]+),(?P<id>\d+)/$', pet.views.car, name='car'),
    url(r'^car/search$', pet.views.board_finder, name='search'),
    url(r'^car/searchBoards$', pet.views.search_boards, name='search_boards'),
    url(r'^friend/accept/(?P<friendship_request_id>\d+)/$', pet.views.friendship_accept, name='friendship_accept'),
    url(r'^friend/cancelss/(?P<username>[\w-]+)/$', pet.views.friendship_cancel, name='friendship_cancel'),
    url(r'^show_followers/remove/(?P<followee_username>[\w-]+)/$', pet.views.follower_remove, name='follower_remove'),
    url(r'^friend/remove/(?P<friendship_request_id>\d+)/$', pet.views.friendship_reject, name='friendship_reject'),
]

message/models.py
from django.db import models

from pet.models import Person


class Thread(models.Model):
    subject = models.CharField(max_length=20, blank=True)
    user = models.ForeignKey(Person, on_delete=models.CASCADE)


class Message(models.Model):
    user = models.ForeignKey(Person, related_name='sender', on_delete=models.CASCADE)
    recipient = models.ForeignKey(Person, related_name='recipient', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    body = models.CharField(max_length=1000)
    read = models.BooleanField(default=False)
    sentmessage = models.BooleanField(default=False)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    draft = models.BooleanField(default=False)
    is_deleted_by_sender = models.BooleanField(default=False)
    is_deleted_by_recipient = models.BooleanField(default=False)

    def __unicode__(self):
        return self.body

message/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from message.forms import NewMessageForm, DraftForm, ThreadForm, ReplyForm
from message.models import Person, Message, Thread
from django.core.exceptions import ValidationError


@login_required
def message(request):
    posts = Message.objects.filter(recipient=request.user, sentmessage=True, is_deleted_by_recipient=False).order_by(
        "-created")
    person = Person.objects.get(username=request.user, )
    if request.method == 'POST':
        delete_list = request.POST.get('hidden_field', False)
        if delete_list:
            values = [int(i) for i in delete_list.split("~")]
            m = Message.objects.filter(pk__in=values)
            message = m.filter(recipient=request.user)
            for m in message:
                m.is_deleted_by_recipient = "True"
                m.save()
    paginator = Paginator(posts, 7)

    try:
        page = int(request.GET.get("page", '1'))
    except ValueError:
        page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    return render(request, 'messages.html', {'posts': posts, 'person': person})


@login_required
def draft(request):
    person = Person.objects.get(username=request.user)
    posts = Message.objects.filter(recipient=request.user, draft=True).order_by("-created")
    if request.method == 'POST':
        delete_list = request.POST.get('hidden_field', False)
        if delete_list:
            values = [int(i) for i in delete_list.split("~")]
            m = Message.objects.filter(pk__in=values)
            m = m.filter(recipient=request.user, draft=True)
            m.delete()
            return HttpResponseRedirect(reverse('message:draft'))

    paginator = Paginator(posts, 7)

    try:
        page = int(request.GET.get("page", '1'))
    except ValueError:
        page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    return render(request, 'draft.html', {'posts': posts, 'person': person, })


@login_required
def sent_message(request):
    person = Person.objects.get(username=request.user)
    posts = Message.objects.filter(user=request.user, sentmessage=True, is_deleted_by_sender=False).order_by("-created")
    sentmessage = "Hello"
    if request.method == 'POST':
        delete_list = request.POST.get('hidden_field', False)
        if delete_list:
            values = [int(i) for i in delete_list.split("~")]
            m = Message.objects.filter(pk__in=values)
            message = m.filter(user=request.user, sentmessage=True)
            for m in message:
                m.is_deleted_by_sender = "True"
                m.save()

    paginator = Paginator(posts, 7)

    try:
        page = int(request.GET.get("page", '1'))
    except ValueError:
        page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    return render(request, 'sentmessage.html', {'posts': posts, 'person': person, 'sent_message': sentmessage})


@login_required
def read_sent_message(request, id):
    try:
        messages = Message.objects.get(pk=id, user=request.user, sentmessage=True, draft=False)
    except Message.DoesNotExist:
        return HttpResponseRedirect(reverse('world:display'))

    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            id = request.POST.get('hidden_field', False)
            try:
                messages = Message.objects.get(pk=id, user=request.user, sentmessage=True, draft=False)

            except Message.DoesNotExist:
                return HttpResponseRedirect(reverse('world:login_request'))

            body = form.cleaned_data['body']

            Message.objects.create(user=request.user, recipient=messages.recipient, body=body, thread=messages.thread,
                                   sentmessage=True, read=False)
            return HttpResponseRedirect(reverse('message:message'))

    message = Message.objects.filter(thread=messages.thread).filter(created__lte=messages.created)
    person = Person.objects.get(username=request.user)

    initial = {}
    initial.update({'hidden_field': messages.id})
    form = ReplyForm(initial=initial)

    return render(request, 'read.html', {'messages': messages, 'form': form, 'message': message, 'person': person})


@login_required
def read(request, id):
    try:
        messages = Message.objects.get(pk=id, recipient=request.user)
    except Message.DoesNotExist:
        return HttpResponseRedirect(reverse('world:display'))
    messages.read = True
    messages.save()
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            id = form.cleaned_data['hidden_field']

            try:
                messages = Message.objects.get(pk=id, recipient=request.user, sentmessage=True, draft=False)

            except Message.DoesNotExist or Thread.DoesNotExist:
                return HttpResponseRedirect(reverse('world:login_request'))
            person = Person.objects.get(username=messages.user)
            if person.inbox == "D":
                return HttpResponseRedirect(reverse('message:message'))
            body = form.cleaned_data['body']

            Message.objects.create(user=request.user, recipient=messages.user, body=body, thread=messages.thread,
                                   sentmessage=True, read=False)
            return HttpResponseRedirect(reverse('message:message'))
        else:
            raise ValidationError

    message = Message.objects.filter(thread=messages.thread).filter(created__lte=messages.created)
    person = Person.objects.get(username=request.user)

    initial = {}
    initial.update({'hidden_field': messages.id})
    form = ReplyForm(initial=initial)

    return render(request, 'read.html', {'messages': messages, 'form': form, 'message': message, 'person': person})


@login_required
def create(request):
    person = Person.objects.get(username=request.user)
    form = NewMessageForm(request)
    if request.POST.get('_send', False):
        form = NewMessageForm(request, request.POST)
        if form.is_valid():
            recipient = form.cleaned_data['recipient']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            if recipient:
                thread = Thread.objects.create(subject=subject, user=request.user)
                Recipient = Person.objects.get(username=request.user)
                if Recipient.inbox == "D":
                    return HttpResponseRedirect(reverse('message:message'))
                message = Message.objects.create(user=request.user, recipient=recipient, body=message, thread=thread,
                                                 sentmessage=True, read=False)
                return HttpResponseRedirect(reverse('message:message'))
            else:
                thread = Thread.objects.create(subject=subject, user=request.user)
                Message.objects.create(user=request.user, recipient=request.user, body=message, thread=thread,
                                       draft=True)
                return HttpResponseRedirect(reverse('message:message'))

    elif request.POST.get('_save', False):
        form = NewMessageForm(request, request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            thread = Thread.objects.create(subject=subject, user=request.user)
            Message.objects.create(user=request.user, recipient=request.user, body=message, thread=thread, draft=True,
                                   sentmessage=False)
            return HttpResponseRedirect(reverse('message:message'))
    return render(request, 'create.html', {'form': form, 'person': person})


@login_required
def read_draft(request, id):
    try:
        messages = Message.objects.get(pk=id, recipient=request.user)
    except Message.DoesNotExist:
        return HttpResponseRedirect(reverse('world:display'))
    thread = Thread.objects.get(message=messages)
    initial = {}
    initial.update({'hidden_field': messages.id})
    draft = DraftForm(request, instance=messages, initial=initial)
    thread = ThreadForm(instance=thread)
    person = Person.objects.get(username=request.user)

    if request.method == 'POST':
        id = request.POST.get('hidden_field', False)
        form = ThreadForm(request.POST)
        forms = DraftForm(request, request.POST)
        if form.is_valid() and forms.is_valid():

            m = Message.objects.get(pk=id, )
            recipient = forms.cleaned_data['recipient']
            subject = form.cleaned_data['subject']
            body = forms.cleaned_data['body']
            person = Person.objects.get(username=request.user)

            m.user = request.user
            m.recipient = recipient
            m.body = body
            m.draft = False
            m.sentmessage = True
            m.save()
            return HttpResponseRedirect(reverse('message:message'))
        else:
            ctx = {'DraftForm': forms, 'ThreadForm': form, 'person': person}
            return render(request, 'create.html', ctx)

    return render(request, 'create.html', {'DraftForm': draft, 'ThreadForm': thread, 'person': person})

message/templates/read.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
{% load static %}
<link rel="stylesheet" href="{% static "css/inbox.css" %}">
{% load thumbnail %}
<div class="box3"></div>
<div class="box4"></div>
<a class="theLink" href="{% url "world:profile" person.slug %}">
    <div class="box9">Profile</div>
</a>
<a class="theLink" href="{% url "world:show_following" %}">
    <div class="box10">Following</div>
</a>
<a class="theLink" href="{% url "world:board_finder" %}">
    <div class="box11">Explore</div>
</a>
<a class="theLink" href="{% url "world:board_creator" %}">
    <div class="box12">Create</div>
</a>
<div class="cake1">SparkaLight</div>
<a class="theLink" href="{% url "message:create" %}">
    <div class="box16">New</div>
</a>
<a class="theLink" href="{% url "message:draft" %}">
    <div class="box17">draft</div>
</a>
<a class="theLink" href="{% url "message:sent_message" %}">
    <div class="box18">Sent Message</div>
</a>
<div class="box13">inbox</div>

<div class="box23"></div>

{% if messages %}


    <span class="d">{% if messages.user.image %}{% thumbnail messages.user.image "60x60" crop="center" as im %}
        <img src="{{ im.url }}">{% endthumbnail %}{% endif %}</span>
    <span class="send"><span class="sender">From : {{ messages.user.username }}</span></span>
    <span class="send"><span class="recipient">To : {{ messages.recipient.username }}</span></span>


{% endif %}




<div class="box22">


    {% for m in message %}

        <div class="wrapper">
            <div class="user">{{ m.user.username }} </div>
            <div class="message">{{ m.body }}</div>
        </div>

    {% endfor %}



    <form method="POST">{% csrf_token %}
        {{ form.body }}{{ form.hidden_field }}
        <input type="submit" value="send" class="sen"/>

    </form>


</div>

{{ form.body.errors }}

message/templates/sentmessage.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    {% load static %} {% load thumbnail %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content=""> {% load static %}
    <title>SparkaLight</title>
    <!-- Bootstrap core CSS -->
    <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static '/css/theme.css' %}">
    <!-- Custom styles for this template -->
    <!--  <link href="style.css" rel="stylesheet"> -->
</head>

<body class="blue-bg mt-2 inbox">


    <div class="container pt-2 sp-h-100">
        <header>

            <div class="row sp-head-holder">
                <div class="col-sm-4 logo-holder order-sm-2 m-blue-bg">
                    <a href="/" class="logo hs white">SparkaLight</a>
                </div>

                <div class="col-sm-3 ml-auto order-sm-1 l-yellow-bg m-blue-border sp-nav-holder">
                    <ul class="list-inline sp-nav mb-0 text-sm-center">
                        <li class="list-inline-item">
                            <a href="{% url "world:profile" person.slug %}" class="hs blue">Profile</a>
                        </li>
                        <li class="list-inline-item">
                            <a href="{% url "world:show_following" %}" class="hs blue">Following</a>
                        </li>
                    </ul>
                </div>


                <div class="col-sm-3 mr-auto order-sm-3 l-yellow-bg m-blue-border sp-nav-holder">
                    <ul class="list-inline mb-0 sp-nav text-sm-center">
                        <li class="list-inline-item">
                            <a href="{% url "world:board_finder" %}" class="hs blue">Explore</a>
                        </li>
                        <li class="list-inline-item">
                            <a href="{% url "message:create" %}" class="hs blue">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>

        <div class="row title-holder">
            <div class="col-sm-8 mb-1 mr-auto ml-auto m-blue-bg white text-center">
                {% if sentmessage %}
                <h2 class="hs my-0">Draft</h2>
                
                {% else %}
                <h2 class="hs my-0">Send Messages</h2>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-2 p-0 order-md-2">
                <ul class="mail-menu list-unstyled">
                    <li class="orange-link lw">
                        <a href="{% url "message:create" %}">Create</a>
                    </li>
                    <li class="blue-link lw">
                        <a href="{% url "message:message" %}">Inbox</a>
                    </li>
                    <li class="yellow-link lw">
                        {% if sentmessage %}
                        <a href="{% url "message:draft" %}">Draft</a>
                        {% else %}
                        <a href="{% url "message:sent_message" %}">Send Message</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
            <div class="col-md-8 ml-auto white-bg pt-3 pb-3 order-md-1">
                <table class="table table-bordered wb">
                    <thead>
                        <tr>
                            <th scope="col" class="blue-bg white lw">Sender</th>
                            <th scope="col" class="blue-bg white lw">Subject</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <form method="POST" id="messageForm">
                            {% csrf_token %} {% for m in posts %}
                            <tr>
                                {% if m.read == False %}
                                <a class="theLink" href="{% url "message:read_draft" m.id %}">
                                    <td>{{ m.user.username }}</td>
                                </a>
                                <td>{{ m.body }}</td>
                                <td>
                                    <input type="checkbox" value="{{ m.id }}" aria-label="Checkbox for following text input" class="messages id_check">
                                </td>
                                {% else %}

                                <a class="theLink" href="{% url "message:read_draft" m.id %}">
                                    <td>{{ m.user.username }}</td>
                                </a>
                                <td>{{ m.body }}</td>
                                <td>
                                    <input type="checkbox" value="{{ m.id }}" aria-label="Checkbox for following text input" class="messages id_check">
                                </td>
                                {% endif %} {% endfor %}
                                <td>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                </td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="text-right">
                                    <input type="button" id="deleteBttn" value="Delete" class="delete lw">
                                </td>
                                <td>
                                    <input type="checkbox" aria-label="Checkbox for following text input">
                                </td>
                            </tr>
                        </form>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <!-- container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="{% static "javascript/jquery-1.9.1.min.js" %}"></script>
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            $("#deleteBttn").click(function (event) {
                var selectedList = "";
                var selectCount = $(":checked.messages").length;
                if (selectCount == 0) {
                    alert("Please select atleast one message to delete.");
                    return;

                }
                else if (confirm("Are you sure you want to delete the selected message(s)?")) {
                    $(":checked.messages").each(function () {
                        if (selectedList == "") {
                            selectedList = $(this).val();
                        }
                        else {
                            selectedList += "~" + $(this).val();
                        }
                    });
                    if (selectedList != "") {
                        $("#hidden_field").val(selectedList);
                        $("#messageForm").submit();
                    }
                }
            });
        });
    </script>

    <script type="text/javascript">
        function toggle(source) {
            checkboxes = document.getElementsByName('check');
            for (var i = 0, n = checkboxes.length; i < n; i++) {
                checkboxes[i].checked = source.checked;
            }
        }
    </script> {% if posts.object_list and posts.paginator.num_pages > 1 %}
    <div class="pagination" style="margin-top: 20px; margin-left: -20px; ">
        <span class="step-links">
            {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">newer entries &lt;&lt; </a>
            {% endif %}
            <span class="current">
                &nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
            </span>
            {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}"> &gt;&gt; older entries</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</body>
</html>


<!--
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
{% load static %}
<link rel="stylesheet" href="{% static "css/inbox.css" %}">

<script type="text/javascript" src="{% static "javascript/jquery-1.10.1.min.js" %}"></script>
<script type="text/javascript">
    $(document).ready(function () {

        $("#deleteBttn").click(function (event) {
            var selectedList = "";
            var selectCount = $(":checked.messages").length;
            if (selectCount == 0) {
                alert("Please select atleast one message to delete.");
                return;

            }
            else if (confirm("Are you sure you want to delete the selected message(s)?")) {
                $(":checked.messages").each(function () {
                    if (selectedList == "") {
                        selectedList = $(this).val();
                    }
                    else {
                        selectedList += "~" + $(this).val();
                    }
                });
                if (selectedList != "") {
                    $("#hidden_field").val(selectedList);
                    $("#messageForm").submit();
                }
            }
        });
    });
</script>

<script type="text/javascript">
    function toggle(source) {
        checkboxes = document.getElementsByName('check');
        for (var i = 0, n = checkboxes.length; i < n; i++) {
            checkboxes[i].checked = source.checked;
        }
    }
</script>


<div class="box3"></div>
<div class="box4"></div>
<a class="theLink" href="{% url "world:profile" person.slug %}">
    <div class="box9">Profile</div>
</a>
<a class="theLink" href="{% url "world:show_following" %}">
    <div class="box10">Following</div>
</a>
<a class="theLink" href="{% url "world:board_finder" %}">
    <div class="box11">Explore</div>
</a>
<a class="theLink" href="{% url "world:board_creator" %}">
    <div class="box12">Create</div>
</a>
<div class="cake1">SparkaLight</div>
<a class="theLink" href="{% url "message:create" %}">
    <div class="box16">Create</div>
</a>
<a class="theLink" href="{% url "message:message" %}">
    <div class="box17">Inbox</div>
</a>

{% if sentmessage %}
    <a class="theLink" href="{% url "message:draft" %}">
        <div class="box18">draft</div>
    </a>
{% else %}

    <a class="theLink" href="{% url "message:sent_message" %}">
        <div class="box18">Sent Message</div>
    </a>
    {% endif %}

<div class="box13">sent messages</div>

<div class="box15">

    <div class="box19">Sender</div>
    <div class="box20">Subject</div>


    <form method="POST" id="messageForm">
        {% csrf_token %}




        {% for m in posts %}

            <a class="theLink" href="{% url "message:read_sent_message" m.id %}">

                <div class="username">{{ m.user.username }}</div>
                <div class="description">{{ m.body }}</div>
            </a>

            <input type="checkbox" name="check" value="{{ m.id }}" class="messages id_check">


            </a>




        {% endfor %}


        <input type="hidden" value="" id="hidden_field" name="hidden_field"/>
        <input type="button" id="deleteBttn" value="Delete" class="box21"/>

    </form>

</div>


</div>


<!-- Next/Prev page links  -->
<!--
{% if posts.object_list and posts.paginator.num_pages > 1 %}
    <div class="pagination" style="margin-top: 20px; margin-left: -20px; ">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?page={{ posts.previous_page_number }}">newer entries &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
                </span>

                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}"> &gt;&gt; older entries</a>
                {% endif %}
            </span>
    </div>
{% endif %}

<input type="checkbox" onClick="toggle(this)" class="inbox"/>-->