accounts/urls.py
import django.contrib.auth.views
from django.conf.urls import url

import accounts.views

urlpatterns = [
    url(r'^forgot-password/$', accounts.views.forgot_password, name="forgot-password"),
    url(r'^change-email/$', accounts.views.change_email, name="change_email"),
    url(r'^termination/$', accounts.views.termination, name="termination"),
    url(r'^change-password/$', django.contrib.auth.views.password_change, name='change'),
    url(r'^password-changed/$', django.contrib.auth.views.password_change_done),
    url(r'^password_reset_done/$', django.contrib.auth.views.password_reset_done),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.http import HttpResponse
import django.contrib.auth.urls

import pet.urls
import message.urls
import accounts.urls
import pet.views

admin.autodiscover()

urlpatterns = [
    url(r'', include(pet.urls, namespace='world')),
    url(r'^$', pet.views.index),
    url(r'^account/', include(django.contrib.auth.urls)),
    url(r'^account/', include(accounts.urls)),
    url(r'^secert/', include(admin.site.urls)),
    url(r'^message/', include(message.urls, namespace="message")),
    url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain")),
    # url(r'^admin/', include('admin_honeypot.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

pet/urls.py
from django.conf.urls import url

import pet.views

urlpatterns = [
    url(r'^display/$', pet.views.display, name='display'),
    url(r'^picture/$', pet.views.picture_creator, name='picture_creator'),
    url(r'^board/$', pet.views.board_creator, name='board_creator'),
    url(r'^register/$', pet.views.pet_registration, name='petRegistration'),
    url(r'^login/$', pet.views.login_request, name='login_request'),
    url(r'^logout/$', pet.views.logout_request, name='logout_request'),
    url(r'^profile/(?P<slug>[-\w\d]+)/$', pet.views.profile, name='profile'),
    url(r'^friend/add/(?P<to_username>[\w-]+)/$', pet.views.friendship_add_friend, name='friendship_add_friend'),
    url(r'^show_followers/add/(?P<followee_username>[\w-]+)/$', pet.views.follower_add, name='follower_add'),
    url(r'^archive/$', pet.views.archive, name='archive'),
    url(r'^board/(?P<slug>[-\w\d]+),(?P<id>\d+)/(?P<picture_id>\d+)$', pet.views.description, name='description'),
    url(r'^show_following/$', pet.views.show_followers, name='show_followers'),
    url(r'^boardfinder/$', pet.views.board_finder, name='board_finder'),
    url(r'^boardeditor/$', pet.views.board_editor, name='board_editor'),
    url(r'^changepicture/(?P<picture_id>\d+)/$', pet.views.change_picture, name='change_picture'),
    url(r'^show_following/(?P<slug>[-\w\d]+)/cancelfriend/$', pet.views.cancel_friend, name='cancel_friend'),
    url(r'^show_following/(?P<slug>[-\w\d]+)/addfriend/$', pet.views.add_friend, name='add_friend'),
    url(r'^my_friend/$', pet.views.my_friend, name='my_friend'),
    url(r'^Follow/$', pet.views.show_following, name='show_following'),
    url(r'^sparkprofile/$', pet.views.spark_profile, name='spark_profile'),
    url(r'^search_person/$', pet.views.search_person, name='search_person'),
    url(r'^followingall/$', pet.views.following_all, name='following_all'),
    url(r'^whatisparkalight/$', pet.views.whatspark, name='whatspark'),
    url(r'^contact/$', pet.views.contacts, name='contact'),
    url(r'^edit_friend_func/$', pet.views.edit_friend_func, name='edit_friend_func'),
    url(r'^friend_star/(?P<slug>[-\w\d]+)/$', pet.views.friend_star, name='friend_star'),
    url(r'^term-and-condition/$', pet.views.term, name='term'),
    url(r'^privacy-policy/$', pet.views.privacy, name='privacy'),
    url(r'^faq/$', pet.views.faq, name='faq'),
    url(r'^car/like$', pet.views.like, name='like'),
    url(r'^car/postComment$', pet.views.post_comment, name='post_comment'),
    url(r'^car/getComment$', pet.views.get_comment, name='get_comment'),
    url(r'^car/deleteComment$', pet.views.delete_comment, name='delete_comment'),
    url(r'^board/(?P<slug>[-\w\d]+),(?P<id>\d+)/$', pet.views.car, name='car'),
    url(r'^car/search$', pet.views.board_finder, name='search'),
    url(r'^car/searchBoards$', pet.views.search_boards, name='search_boards'),
    url(r'^friend/accept/(?P<friendship_request_id>\d+)/$', pet.views.friendship_accept, name='friendship_accept'),
    url(r'^friend/cancelss/(?P<username>[\w-]+)/$', pet.views.friendship_cancel, name='friendship_cancel'),
    url(r'^show_followers/remove/(?P<followee_username>[\w-]+)/$', pet.views.follower_remove, name='follower_remove'),
    url(r'^friend/remove/(?P<friendship_request_id>\d+)/$', pet.views.friendship_reject, name='friendship_reject'),
]

accounts/models.py
from django.db import models


class Question(models.Model):
    image = models.ImageField(upload_to='photos')
    answer = models.CharField(max_length=255)

    def delete(self, *args, **kwargs):
        self.image.delete(False)
        super(Question, self).delete(*args, **kwargs)

accounts/forms.py
from django import forms


class TerminationForm(forms.Form):
    final = forms.CharField(widget=forms.Textarea, max_length=500, required=False)

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import password_reset
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from friendship.models import Friend, Follow
from sorl.thumbnail import delete
from accounts.forms import TerminationForm
from pet.forms import EmailForm
from pet.models import Person, Board, Picture


def forgot_password(request):
    if request.method == 'POST':
        return password_reset(request, from_email=request.POST.get('email'))
    return render(request, 'forgot_password.html')


@login_required
def change_email(request):
    form = EmailForm(request)
    if request.method == "POST":
        form = EmailForm(request, request.POST)
        if form.is_valid():
            user = Person.objects.get(username=request.user)
            email = form.cleaned_data['email']
            user.email = email
            user.save()
            return HttpResponseRedirect(reverse('world:profile', kwargs={'username': user.slug}))

    return render(request, 'email.html', {'form': form})


@login_required
def termination(request):
    form = TerminationForm()
    if request.method == "POST":
        form = TerminationForm(request.POST)
        if form.is_valid():
            person = Person.objects.get(username=request.user)
            board = Board.objects.filter(user=request.user)
            picture = Picture.objects.filter(board=board)
            for p in picture:
                delete(p.image)
                p.delete()
            for b in board:
                b.delete()
            friend = Friend.objects.friends(person)
            for f in friend:
                Friend.objects.remove_friend(person, f)
            following = Follow.objects.following(request.user)
            for f in following:
                Follow.objects.remove_follower(person, f)
            for f in following:
                Follow.objects.remove_follower(person, f)
            requests = Friend.objects.unread_requests(user=request.user)
            for f in requests:
                f.delete()
            person.is_active = False
            person.email = None
            person.date_of_birth = None
            person.image.delete()
            person.save()
            return HttpResponseRedirect(reverse('world:logout_request'))
    return render(request, 'termination.html', {'form': form})

accounts/templates/email.html
<!DOCTYPE html>
<html lang="en-us">
<head>
    {% load static %}
    <title>Password change</title>
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/base.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}"/>
    <!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/admin/css/ie.css" /><![endif]-->

    <script type="text/javascript">window.__admin_media_prefix__ = "/static/admin/";</script>

    <meta name="robots" content="NONE,NOARCHIVE"/>
</head>


<body class="">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

            <h1 id="site-name">Sparkalight </h1>

        </div>


    </div>

    <!-- END Header -->

    <div class="breadcrumbs">
        <a href="{% url "world:display" %}">Back</a>
        &rsaquo; Password change
    </div>


    <!-- Content -->
    <div id="content" class="colM">


        <div id="content-main">

            <form action="" method="post">
                <div style='display:none'>{% csrf_token %}</div>
                <div>


                    <h2>Change Email</h2>

                    <p>You may change your email address by inserting your new one</p>

                    <fieldset class="module aligned wide">
                        <div class="form-row">

                            <label for="id_old_password" class="required">Old Email:</label>{{ form.old }}
                        </div>
                        {{ form.old.errors }}
                        <div class="form-row">

                            <label for="id_old_password" class="required">New Email:</label>{{ form.email }}
                        </div>
                        {{ form.email.errors }}


                    </fieldset>

                    <div class="submit-row">

                        <input type="submit" value="Change my email" class="default"/>
                    </div>


            </form>
        </div>


        <br class="clear"/>
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

accounts/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en-us">
<head>
    {% load static %}
    <title>Password change</title>
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/base.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}"/>
    <!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/admin/css/ie.css" /><![endif]-->

    <script type="text/javascript">window.__admin_media_prefix__ = "/static/admin/";</script>

    <meta name="robots" content="NONE,NOARCHIVE"/>

    <style type="text/css">
        .sam {
            position: absolute;
            left: 20px;
            top: 280px;
        }

        .friend {
            position: absolute;
            left: 20px;
            top: 500px;
        }

        .form {
            position: absolute;
            left: 20px;
            top: 230px;
            color: #272822;
        }

        .picture {
            position: absolute;
            left: 20px;
            top: 80px;
        }

        label {
            color: #333333;
        }

        .captcha {
            color: #333333;
            position: absolute;
            left: 20px;
            top: 300px;
        }

    </style>


</head>


<body class="">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

            <h1 id="site-name">Sparkalight </h1>

        </div>


    </div>

    <!-- END Header -->

    <div class="breadcrumbs">
        <a class="theLink" href="{% url "world:login_request" %}">Home</a>
        &rsaquo; Password change
    </div>

    <form method="post" action="{% url "forgot-password" %}">


        Forgot Password

        {% csrf_token %}
        <p>Please enter your email address.
            You will receive a link to create a new password via email.</p>

        <input type="email" name="email"
               placeholder="Your e-mail"><br/>

        <button type="submit">Send new password</button>
    </form>

    <div class="captcha">

        {{ form }}
    </div>

accounts/templates/termination.html
<html>
<head>
    <title>Page</title>

    <style type="text/css">
        body {
            background-color: #F5E49C
        }

        .wrapper {
            background-color: #FFFFFF;
            width: 440px;
            height: 530px;
            position: absolute;
            left: 500px;
            top: 100px;
            border-color: #93DBE9;
            border-style: solid;
            border-width: 15px;
        }

        @font-face {
            font-family: Lora;
            src: url('{{ STATIC_URL }}css/Lora-Regular.ttf');
        }

        @font-face {
            font-family: Bellota-Regular;
            src: url('{{ STATIC_URL }}css/Bellota-Regular.otf');
        }

        .font {
            font-family: Lora;
            font-size: 35px;
            color: #93DBE9;
            font-weight: bold;
            position: absolute;
            left: 40px;
            top: 30px;
        }

        .thank {
            color: #72B395;
            font-family: Lora;
            font-weight: bold;
            font-size: 17px;
            position: absolute;
            left: 20px;
            top: 110px;
        }

        #id_final {
            position: absolute;
            left: 20px;
            top: 190px;
            border-style: solid;
            border-color: #DCDCDC;
            width: 390px;
            height: 150px;
            color: #787878;
        }

        .free {
            color: #93DBE9;
            font-family: Lora;
            font-weight: bold;
            font-size: 16px;
            position: absolute;
            left: 20px;
            top: 350px;

        }

        .info {
            color: #B4B4B4;
            font-family: Lora;
            font-weight: bold;
            font-style: italic;
            font-size: 14px;
            position: absolute;
            left: 20px;
            top: 400px;
            text-decoration: underline;

        }

        .submit {
            background-color: #93DBE9;
            font-size: 20px;
            font-family: Lora;
            color: #FFFFFF;
            font-weight: bold;
            border-style: none;
            position: absolute;
            left: 140px;
            top: 480px;
        }

        .ribbon {
            background-color: #93DBE9;
            width: 70px;
            height: 140px;
            position: absolute;
            left: 1170px;
            top: 0px;
            font-family: Bellota-Regular;
            color: #FFFFFF;
            padding-left: 5px;
            font-size: 15px;
        }

        .theLink {
            text-decoration: none;
        }
    </style>
    <form method="POST">{% csrf_token %}


        <div class="wrapper">
            <span class="font"> Account termination </span>
            <span class="thank"> Before you leave , we thank you for using this service and good luck in the future </span>
            {{ form.final }}
            <span class="free"> Feel free to leave a reason for why your leaving </span>
            <span class="info">For more info on how we terminate your account please
check the topic under the heading termination in the terms and condition</span>
            <input type="submit" value="Terminate" class="submit">
        </div>

        <a class="theLink" href="{% url "world:profile" request.user.slug %}">
            <div class="ribbon"><br><br> Return To profile
            </div>
        </a>

    </form>